server:
  port: 9092

spring:
  application:
    name: exemplo-sidecar-server

sidecar:
  port: 9094
  health-uri: http://localhost:9094/health
  
eureka:
  instance:
    virtual-host-name: exemplo-sidecar-server
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/
